### ISSUE TITLE
Clipboard size limit to copy into Clipboard history

### ISSUE THREAD

**Issue by atiris** [edgardmessias/vscode.clipboard-manager#36]
I am using this extension in Linux VSCode Version: 1.37.1. Sometimes I move large inserts scripts (almost 500000 lines) between files.

Every time I copy such amount of data to the clipboard, VSCode it is stuck and blocked for few minutes.

It is possible to limit size of clipboard copied into clipboard manager (like set max limit of 1 megabyte or something) for internal items and items outside the VSCode (ideally separated)?

Because otherwise I always have to remember and turn off this extension before I copy something big like that.

Thanks

**Comment by edgardmessias** [comment]
Hello @atiris, I added a option to limit size of clipboard `clipboard-manager.maxClipboardSize` with default value of `~1MB`.
This solution avoid to save a big clipboard at memory and persist file, but might keep your problem of "freezing", because the unique way to read the clipboard is slow.

Update to version `v1.4.0` and give me a feedback
